<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE GANGLIA_XML [
   <!ELEMENT GANGLIA_XML (GRID|CLUSTER|HOST)*>
      <!ATTLIST GANGLIA_XML VERSION CDATA #REQUIRED>
      <!ATTLIST GANGLIA_XML SOURCE CDATA #REQUIRED>
   <!ELEMENT GRID (CLUSTER | GRID | HOSTS | METRICS)*>
      <!ATTLIST GRID NAME CDATA #REQUIRED>
      <!ATTLIST GRID AUTHORITY CDATA #REQUIRED>
      <!ATTLIST GRID LOCALTIME CDATA #IMPLIED>
   <!ELEMENT CLUSTER (HOST | HOSTS | METRICS)*>
      <!ATTLIST CLUSTER NAME CDATA #REQUIRED>
      <!ATTLIST CLUSTER OWNER CDATA #IMPLIED>
      <!ATTLIST CLUSTER LATLONG CDATA #IMPLIED>
      <!ATTLIST CLUSTER URL CDATA #IMPLIED>
      <!ATTLIST CLUSTER LOCALTIME CDATA #REQUIRED>
   <!ELEMENT HOST (METRIC)*>
      <!ATTLIST HOST NAME CDATA #REQUIRED>
      <!ATTLIST HOST IP CDATA #REQUIRED>
      <!ATTLIST HOST LOCATION CDATA #IMPLIED>
      <!ATTLIST HOST TAGS CDATA #IMPLIED>
      <!ATTLIST HOST REPORTED CDATA #REQUIRED>
      <!ATTLIST HOST TN CDATA #IMPLIED>
      <!ATTLIST HOST TMAX CDATA #IMPLIED>
      <!ATTLIST HOST DMAX CDATA #IMPLIED>
      <!ATTLIST HOST GMOND_STARTED CDATA #IMPLIED>
   <!ELEMENT METRIC (EXTRA_DATA*)>
      <!ATTLIST METRIC NAME CDATA #REQUIRED>
      <!ATTLIST METRIC VAL CDATA #REQUIRED>
      <!ATTLIST METRIC TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRIC UNITS CDATA #IMPLIED>
      <!ATTLIST METRIC TN CDATA #IMPLIED>
      <!ATTLIST METRIC TMAX CDATA #IMPLIED>
      <!ATTLIST METRIC DMAX CDATA #IMPLIED>
      <!ATTLIST METRIC SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRIC SOURCE (gmond) 'gmond'>
   <!ELEMENT EXTRA_DATA (EXTRA_ELEMENT*)>
   <!ELEMENT EXTRA_ELEMENT EMPTY>
      <!ATTLIST EXTRA_ELEMENT NAME CDATA #REQUIRED>
      <!ATTLIST EXTRA_ELEMENT VAL CDATA #REQUIRED>
   <!ELEMENT HOSTS EMPTY>
      <!ATTLIST HOSTS UP CDATA #REQUIRED>
      <!ATTLIST HOSTS DOWN CDATA #REQUIRED>
      <!ATTLIST HOSTS SOURCE (gmond | gmetad) #REQUIRED>
   <!ELEMENT METRICS (EXTRA_DATA*)>
      <!ATTLIST METRICS NAME CDATA #REQUIRED>
      <!ATTLIST METRICS SUM CDATA #REQUIRED>
      <!ATTLIST METRICS NUM CDATA #REQUIRED>
      <!ATTLIST METRICS TYPE (string | int8 | uint8 | int16 | uint16 | int32 | uint32 | float | double | timestamp) #REQUIRED>
      <!ATTLIST METRICS UNITS CDATA #IMPLIED>
      <!ATTLIST METRICS SLOPE (zero | positive | negative | both | unspecified) #IMPLIED>
      <!ATTLIST METRICS SOURCE (gmond) 'gmond'>
]>
<GANGLIA_XML VERSION="3.6.0" SOURCE="gmetad">
<GRID NAME="armgrid" AUTHORITY="http://mastercl/ganglia/" LOCALTIME="1634537651">
<CLUSTER NAME="csnow" LOCALTIME="1634537641" OWNER="unspecified" LATLONG="unspecified" URL="unspecified">
<HOST NAME="snow01" IP="192.168.5.95" REPORTED="1634537635" TN="16" TMAX="20" DMAX="0" LOCATION="192.168.5.95" GMOND_STARTED="1634534915" TAGS="">
<METRIC NAME="rx_pkts_lo" VAL="14.3695" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_pkts_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free" VAL="916.019" TYPE="double" UNITS="GB" TN="156" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total free disk space"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Disk Space Available"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="machine_type" VAL=" ¿ãªª" TYPE="string" UNITS="" TN="336" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="system"/>
<EXTRA_ELEMENT NAME="DESC" VAL="System architecture"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Machine Type"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="bytes_out" VAL="22270.94" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Number of bytes out per second"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Bytes Sent"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_errs_eno2" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted error packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_errs_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="gexec" VAL="OFF" TYPE="string" UNITS="" TN="36" TMAX="300" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="core"/>
<EXTRA_ELEMENT NAME="DESC" VAL="gexec available"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Gexec Status"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="proc_total" VAL="5916" TYPE="uint32" UNITS=" " TN="16" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="process"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total number of processes"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Total Processes"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="vm_pgpgout" VAL="0.0000" TYPE="float" UNITS="ops/s" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory_vm"/>
<EXTRA_ELEMENT NAME="DESC" VAL="pgpgout"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Pages out to disk"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_percent_dev_shm" VAL="100.000000" TYPE="float" UNITS="%" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (%) on /dev/shm"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_percent_dev_shm"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="pkts_in" VAL="42.42" TYPE="float" UNITS="packets/sec" TN="16" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Packets in per second"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Packets Received"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_nice" VAL="0.0" TYPE="float" UNITS="%" TN="16" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Percentage of CPU utilization that occurred while executing at the user level with nice priority"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU Nice"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tcp_outsegs" VAL="42.26333" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="tcp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="outsegs"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="TCP segments sent"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_pkts_eno2" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_pkts_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_speed" VAL="0" TYPE="uint32" UNITS="MHz" TN="36" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="CPU Speed in terms of MHz"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU Speed"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="boottime" VAL="1633500931" TYPE="uint32" UNITS="s" TN="336" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="system"/>
<EXTRA_ELEMENT NAME="DESC" VAL="The last time that the system was started"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Last Boot Time"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_errs_lo" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received error packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_errs_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_bytes_eno1" VAL="22450.8730" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted bytes per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_bytes_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="procstat_gmond_mem" VAL="12272" TYPE="uint32" UNITS="KB" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="procstat"/>
<EXTRA_ELEMENT NAME="DESC" VAL="The total memory utilization"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="procstat_gmond_mem"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_percent_run" VAL="99.992737" TYPE="float" UNITS="%" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (%) on /run"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_percent_run"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_hardware_corrupted" VAL="0" TYPE="float" UNITS="Bytes" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="orig_name" VAL="HardwareCorrupted"/>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="HardwareCorrupted"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Memory HardwareCorrupted"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tcpext_tcploss_percentage" VAL="0.00000" TYPE="float" UNITS="pct" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="tcpext"/>
<EXTRA_ELEMENT NAME="DESC" VAL="TCP percentage loss, tcploss / insegs + outsegs"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="TCP loss percentage"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_errs_eno2" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received error packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_errs_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="vm_vmeff" VAL="0.0000" TYPE="float" UNITS="pct" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory_vm"/>
<EXTRA_ELEMENT NAME="DESC" VAL="VM efficiency"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="VM Efficiency"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_drops_eno2" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted dropped packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_drops_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_absolute_sys_fs_cgroup" VAL="125.761154" TYPE="float" UNITS="GB" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (GB) on /sys/fs/cgroup"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_absolute_sys_fs_cgroup"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_wio" VAL="0.0" TYPE="float" UNITS="%" TN="16" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Percentage of time that the CPU or CPUs were idle during which the system had an outstanding disk I/O request"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU wio"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="vm_pgmajfault" VAL="0.0000" TYPE="float" UNITS="ops/s" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory_vm"/>
<EXTRA_ELEMENT NAME="DESC" VAL="pgmajfault"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Major page fault"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_percent_run_user_1000" VAL="0.000000" TYPE="float" UNITS="%" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (%) on /run/user/1000"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_percent_run_user_1000"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_drops_eno1" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="receive packets dropped per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_drops_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="udp_indatagrams" VAL="3.67940" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="udp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="indatagrams"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="UDP packets in"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="os_name" VAL="Linux" TYPE="string" UNITS="" TN="336" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="system"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Operating system name"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Operating System"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tcp_attemptfails" VAL="0.00000" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="tcp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="attemptfails"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="TCP Failed connection attempts"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="udp_rcvbuferrors" VAL="0.00000" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="udp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="rcvbuferrors"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="UDP Receive buffer errors"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="udp_inerrors" VAL="0.00000" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="udp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="inerrors"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="UDP packet receive errors"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="load_one" VAL="3964.00" TYPE="float" UNITS=" " TN="16" TMAX="70" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="load"/>
<EXTRA_ELEMENT NAME="DESC" VAL="One minute load average"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="One Minute Load Average"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_pkts_eno2" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_pkts_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_bytes_lo" VAL="9821.7969" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted bytes per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_bytes_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="os_release" VAL="4.15.0-156-generic" TYPE="string" UNITS="" TN="336" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="system"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Operating system release date"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Operating System Release"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_total" VAL="982.426" TYPE="double" UNITS="GB" TN="2736" TMAX="1200" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total available disk space"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Total Disk Space"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_user" VAL="100.0" TYPE="float" UNITS="%" TN="16" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Percentage of CPU utilization that occurred while executing at the user level"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU User"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_idle" VAL="0.0" TYPE="float" UNITS="%" TN="16" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Percentage of time that the CPU or CPUs were idle and the system did not have an outstanding disk I/O request"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU Idle"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_bytes_eno2" VAL="0.0000" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received bytes per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_bytes_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_bytes_lo" VAL="9821.7969" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received bytes per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_bytes_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_errs_eno1" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted error packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_errs_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="swap_free" VAL="999420" TYPE="float" UNITS="KB" TN="56" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Amount of available swap memory"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Free Swap Space"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_mapped" VAL="57794560" TYPE="float" UNITS="Bytes" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="orig_name" VAL="Mapped"/>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Mapped"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Memory Mapped"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_intr" VAL="0.0" TYPE="float" UNITS="%" TN="36" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="cpu_intr"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="cpu_intr"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_absolute_dev_shm" VAL="125.761154" TYPE="float" UNITS="GB" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (GB) on /dev/shm"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_absolute_dev_shm"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="entropy_avail" VAL="3413" TYPE="uint32" UNITS="bits" TN="16" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="ssl"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Entropy Available"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Entropy Available"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_cached" VAL="14208680" TYPE="float" UNITS="KB" TN="56" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Amount of cached memory"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Cached Memory"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="pkts_out" VAL="31.15" TYPE="float" UNITS="packets/sec" TN="16" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Packets out per second"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Packets Sent"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="udp_outdatagrams" VAL="3.48051" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="udp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="outdatagrams"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="UDP packets out"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="load_five" VAL="3967.68" TYPE="float" UNITS=" " TN="16" TMAX="325" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="load"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Five minute load average"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Five Minute Load Average"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_steal" VAL="0.0" TYPE="float" UNITS="%" TN="36" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="cpu_steal"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="cpu_steal"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_pkts_eno1" VAL="31.8218" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_pkts_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_num" VAL="80" TYPE="uint16" UNITS="CPUs" TN="36" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total number of CPUs"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU Count"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_dirty" VAL="0" TYPE="float" UNITS="Bytes" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="orig_name" VAL="Dirty"/>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="The total amount of memory waiting to be written back to the disk. "/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Mem waiting to be written to disk"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="load_fifteen" VAL="3680.35" TYPE="float" UNITS=" " TN="16" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="load"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Fifteen minute load average"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Fifteen Minute Load Average"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_writeback" VAL="0" TYPE="float" UNITS="Bytes" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="orig_name" VAL="Writeback"/>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="The total amount of memory actively being written back to the disk."/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Mem actively being written to disk"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_percent_sys_fs_cgroup" VAL="100.000000" TYPE="float" UNITS="%" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (%) on /sys/fs/cgroup"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_percent_sys_fs_cgroup"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_free" VAL="26286736" TYPE="float" UNITS="KB" TN="56" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Amount of available memory"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Free Memory"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tcp_insegs" VAL="32.71679" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="tcp"/>
<EXTRA_ELEMENT NAME="DESC" VAL="insegs"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="TCP segments received"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_sintr" VAL="0.0" TYPE="float" UNITS="%" TN="36" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="cpu_sintr"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="cpu_sintr"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_drops_lo" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted dropped packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_drops_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_errs_eno1" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received error packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_errs_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_drops_eno1" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted dropped packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_drops_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_drops_lo" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="receive packets dropped per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_drops_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_system" VAL="0.0" TYPE="float" UNITS="%" TN="16" TMAX="90" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Percentage of CPU utilization that occurred while executing at the system level"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU System"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tcpext_listendrops" VAL="0.00000" TYPE="float" UNITS="count/s" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="tcpext"/>
<EXTRA_ELEMENT NAME="DESC" VAL="listendrops"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="SYNs sent to LISTENing sockets ignored"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="proc_run" VAL="4104" TYPE="uint32" UNITS=" " TN="16" TMAX="950" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="process"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total number of running processes"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Total Running Processes"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_total" VAL="263740272" TYPE="float" UNITS="KB" TN="336" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total amount of memory displayed in KBs"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Memory Total"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="cpu_aidle" VAL="0.0" TYPE="float" UNITS="%" TN="16" TMAX="3800" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="cpu"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Percent of time since boot idle CPU"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="CPU aidle"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="bytes_in" VAL="21675.04" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="300" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Number of bytes in per second"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Bytes Received"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_pkts_eno1" VAL="39.7275" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_pkts_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_bytes_eno2" VAL="0.0000" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted bytes per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_bytes_eno2"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_buffers" VAL="152944" TYPE="float" UNITS="KB" TN="56" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Amount of buffered memory"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Memory Buffers"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="tx_pkts_lo" VAL="14.3695" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="transmitted packets per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="tx_pkts_lo"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_bytes_eno1" VAL="21434.8125" TYPE="float" UNITS="bytes/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="received bytes per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_bytes_eno1"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="disk_free_absolute_run" VAL="25.150406" TYPE="float" UNITS="GB" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="disk"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Disk space available (GB) on /run"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="disk_free_absolute_run"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="mem_shared" VAL="0" TYPE="float" UNITS="KB" TN="56" TMAX="180" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Amount of shared memory"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Shared Memory"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="swap_total" VAL="999420" TYPE="float" UNITS="KB" TN="336" TMAX="1200" DMAX="0" SLOPE="zero" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="memory"/>
<EXTRA_ELEMENT NAME="DESC" VAL="Total amount of swap space displayed in KBs"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="Swap Space Total"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="procstat_gmond_cpu" VAL="0.1" TYPE="float" UNITS="percent" TN="36" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="procstat"/>
<EXTRA_ELEMENT NAME="DESC" VAL="The total percent CPU utilization"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="procstat_gmond_cpu"/>
</EXTRA_DATA>
</METRIC>
<METRIC NAME="rx_drops_eno2" VAL="0.0000" TYPE="float" UNITS="pkts/sec" TN="16" TMAX="60" DMAX="0" SLOPE="both" SOURCE="gmond">
<EXTRA_DATA>
<EXTRA_ELEMENT NAME="GROUP" VAL="network"/>
<EXTRA_ELEMENT NAME="DESC" VAL="receive packets dropped per sec"/>
<EXTRA_ELEMENT NAME="TITLE" VAL="rx_drops_eno2"/>
</EXTRA_DATA>
</METRIC>